### ISSUE TITLE
Can't run according to instructions

### ISSUE THREAD

**Issue by Krisseck** [reaby/infoscreen3#37]
**Describe the bug**
The website does not open on the host and port specified.

- Ran `npm i`
- Copied the default env file to `.env`

Running `npm start`:

```
> infoscreen3@1.6.4 start
> node --expose-gc ./infoscreen3.js

>> InfoScreen3<<
Infoscreen is now accessible at http://127.0.0.1:3000
>>Start complete.<<<
```

Firefox will not open the page on http//127.0.0.1:3000, and curl says:

`curl: (7) Failed to connect to 127.0.0.1 port 3000 after 0 ms: Couldn't connect to server` 

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox / curl
 - Infoscreen Version: 1.6.

**Comment by reaby** [comment]
> Firefox will not open the page on http//127.0.0.1:3000, and curl says:
your URL string seems to be wrong: it should be starting with http**:**//

**Comment by Krisseck** [comment]
My bad, it was some port issues on my end, works great now!
