### ISSUE TITLE
Ability to view info screen without logging in

### ISSUE THREAD

**Issue by VibroAxe** [reaby/infoscreen3#38]
## Anonymous access to infoscreen without username or password 

As a general user on the network in the venue I would like to be able to access a screen without logging in. We use this project for LAN parties and would like to use this to allow keyboard raspberry pi's to be preconfigured with the viewscreen url without having to login.

## Alternatives 

Could accept logging in using a url parameter for credentials

**Comment by reaby** [comment]
Implemented this with accesskey mechanism using url parameter.

**Comment by VibroAxe** [comment]
@reaby thanks, thats really helpful and working well. 10/10 for fast response, would FR again :D
